version: '3.4'

services:
  # traefik:
  #   image: "traefik:v3.0.0-beta4"
  #   ports:
  #     - target: 80
  #       published: 80
  #       mode: host
  #     - target: 443
  #       published: 443
  #       mode: host
  #   deploy:
  #     placement:
  #       constraints:
  #         # Make the traefik service run only on the node with this label
  #         # as the node with it has the volume for the certificates
  #         - node.labels.traefik-public.traefik-public-certificates == true
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.traefik-public-http.rule=Host(`monitor.maltego.local`)
  #     - traefik.http.routers.traefik-public-http.entrypoints=http
  #     - traefik.http.services.traefik-public.loadbalancer.server.port=8080
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   command:
  #     - --providers.docker
  #     - --providers.docker.exposedbydefault=false
  #     - --entrypoints.http.address=:80
  #     - --entrypoints.http.address=:443
  #     - --api
  #     - --api.dashboard=true
  #     - --api.insecure=true
      #- --log.level=DEBUG

  qdrant:
    image: "qdrant/qdrant"
    hostname: qdrant
    ports:
      - "6333:6333"

  infinity:
    image: "michaelf34/infinity"
    hostname: infinity
    command: --model-name-or-path BAAI/bge-small-en
    ports:
      - "7997:7997"

  neo4j:
    hostname: neo4j
    restart: always
    image: neo4j:5.17
    volumes:
      - '$HOME/startgpt/neo4j/data:/data'
      - '$HOME/startgpt/neo4j/conf/:/conf/'
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_apoc_uuid_enabled=true
      - server.memory.heap.initial_size=512m
      - server.memory.heap.max_size=2G
      - server.default_listen_address=0.0.0.0
      - initial.dbms.default_database=neo4j
      - NEO4J_AUTH=neo4j/redbull_wildberry

  notioncrawler:
    platform: "linux/amd64"
    restart: always
    build:
      context: ./apps/notioncrawler
      dockerfile: Dockerfile
    depends_on:
      - neo4j
    environment:
      NEO4J_URL: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASS: redbull_wildberry
      VECTOR_QUEUE_URL: http://vectordb_sync:5000
    env_file:
      - .env
      - .env.local

  vectordb_sync:
    hostname: vectordb_sync
    ports:
      - "5000:5000"
    platform: "linux/amd64"
    restart: always
    build:
      context: ./apps/vectordb_sync
      dockerfile: Dockerfile
    depends_on:
      - neo4j
      - qdrant
    environment:
      NEO4J_URL: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASS: redbull_wildberry
      QDRANT_URL: qdrant:6333
      QDRANT_COLLECTION_NAME: startgpt
      INFINITY_URL: http://infinity:7997/v1
      INFINITY_MODEL: BAAI/bge-small-en
    env_file:
      - .env
      - .env.local
