version: '3.4'

services:
  qdrant:
    image: "qdrant/qdrant"
    hostname: qdrant
    ports:
      - "6333:6333"

  infinity:
    image: "michaelf34/infinity"
    hostname: infinity
    command: --model-name-or-path BAAI/bge-small-en-v1.5
    ports:
      - "7997:7997"

  redis:
    image: "redis"
    hostname: redis
    ports:
      - "6379:6379"
    build:
      context: ./apps/redis
      dockerfile: Dockerfile

  neo4j:
    hostname: neo4j
    restart: always
    image: neo4j:5.17
    volumes:
      - '$HOME/startgpt/neo4j/data:/data'
      - '$HOME/startgpt/neo4j/conf/:/conf/'
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_apoc_uuid_enabled=true
      - server.memory.heap.initial_size=512m
      - server.memory.heap.max_size=2G
      - server.default_listen_address=0.0.0.0
      - initial.dbms.default_database=neo4j
      - NEO4J_AUTH=neo4j/redbull_wildberry

  notioncrawler:
    platform: "linux/amd64"
    restart: always
    build:
      context: ./apps/notioncrawler
      dockerfile: Dockerfile
    depends_on:
      - neo4j
    ports:
      - "8000:8000"
    environment:
      NEO4J_URL: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASS: redbull_wildberry
      VECTOR_QUEUE_URL: http://vectordb_sync:5000
      CORS: "*"
    env_file:
      - .env
      - .env.local

  dashboard:
    build:
      context: ./apps/dashboard
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"

  vectordb_sync:
    hostname: vectordb_sync
    ports:
      - "5000:5000"
    platform: "linux/amd64"
    restart: always
    build:
      context: ./apps/vectordb_sync
      dockerfile: Dockerfile
    depends_on:
      - neo4j
      - qdrant
      - infinity
      - redis
    environment:
      NEO4J_URL: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASS: redbull_wildberry
      QDRANT_URL: http://qdrant:6333
      QDRANT_COLLECTION_NAME: startgpt
      INFINITY_URL: http://infinity:7997
      INFINITY_MODEL: bge-small-en-v1.5
    env_file:
      - .env
      - .env.local

  slackbot:
    hostname: slackbot
    restart: always
    build:
      context: ./apps/slackbot
      dockerfile: Dockerfile
    depends_on:
      - qdrant
      - infinity
    environment:
      QDRANT_URL: http://qdrant:6333
      QDRANT_COLLECTION_NAME: startgpt
      INFINITY_URL: http://infinity:7997
      INFINITY_MODEL: BAAI/bge-small-en-v1.5
    env_file:
      - .env
      - .env.local

