version: "3.4"

services:
  traefik:
    image: "traefik:v3.0.0-beta4"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.traefik-public.traefik-public-certificates == true
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.traefik-http.rule=Host(`traefik.start-rag.startmunich.de`)
      - traefik.http.routers.traefik-http.entrypoints=web
      - traefik.http.routers.traefik-http.middlewares=https-redirect
      - traefik.http.routers.traefik-https.rule=Host(`traefik.start-rag.startmunich.de`)
      - traefik.http.routers.traefik-https.entrypoints=webs
      - traefik.http.routers.traefik-https.tls=true
      - traefik.http.routers.traefik-https.service=traefik
      - traefik.http.routers.traefik-https.tls.certresolver=mycaresolver
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=webs
      - --entrypoints.web.http.redirections.entrypoint.scheme=webs
      - --entrypoints.webs.address=:443
      - --entrypoints.webs.http.tls.certresolver=myresolver
      - --certificatesresolvers.mycaresolver.acme.email=${EMAIL?Variable not set}
      - --certificatesresolvers.mycaresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.mycaresolver.acme.tlschallenge=true
      - --api
      - --api.dashboard=true
      - --api.insecure=true
      - --log.level=DEBUG

  qdrant:
    image: "qdrant/qdrant"
    hostname: qdrant
    expose:
      - "6333"

  infinity:
    image: "michaelf34/infinity"
    hostname: infinity
    command: --model-name-or-path BAAI/bge-large-en-v1.5
    expose:
      - "7997"

  neo4j:
    hostname: neo4j
    restart: always
    image: neo4j:5.17
    volumes:
      - "$HOME/startgpt/neo4j/data:/data"
      - "$HOME/startgpt/neo4j/conf/:/conf/"
    expose:
      - "7474"
      - "7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_apoc_uuid_enabled=true
      - server.memory.heap.initial_size=512m
      - server.memory.heap.max_size=2G
      - server.default_listen_address=0.0.0.0
      - initial.dbms.default_database=neo4j
      - NEO4J_AUTH=neo4j/redbull_wildberry

  redis:
    image: ghcr.io/startmunich/redis:latest
    hostname: redis
    expose:
      - "6379"

  notioncrawler:
    image: ghcr.io/startmunich/notioncrawler:latest
    restart: always
    depends_on:
      - neo4j
    expose:
      - "5001"
    environment:
      NEO4J_URL: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASS: redbull_wildberry
      VECTOR_QUEUE_URL: http://vectordb_sync:5000
      SPACE_ID: $SPACE_ID
      START_PAGE_ID: $START_PAGE_ID
      TOKEN_V2: $TOKEN_V2
      PORT: 5001
      CORS: https://monitor.start-rag.startmunich.de
      RERUN_DELAY_SEC: $RERUN_DELAY_SEC
      MEILISEARCH_URL: http://meilisearch:7700
      MEILISEARCH_API_TOKEN: redbull_blueberry
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_TOKEN: $INFLUXDB_ADMIN_TOKEN
      INFLUXDB_ORG: start_munich
      INFLUXDB_BUCKET: startgpt
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.notioncrawler-http.rule=Host(`crawler.start-rag.startmunich.de`)
      - traefik.http.routers.notioncrawler-http.entrypoints=web
      - traefik.http.routers.notioncrawler-http.middlewares=https-redirect
      - traefik.http.routers.notioncrawler-https.rule=Host(`crawler.start-rag.startmunich.de`)
      - traefik.http.routers.notioncrawler-https.entrypoints=webs
      - traefik.http.routers.notioncrawler-https.tls=true
      - traefik.http.routers.notioncrawler-https.service=notioncrawler
      - traefik.http.routers.notioncrawler-https.tls.certresolver=mycaresolver
      - traefik.http.services.notioncrawler.loadbalancer.server.port=5001

  dashboard:
    image: ghcr.io/startmunich/dashboard:latest
    expose:
      - "3000"
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.dashboard-http.rule=Host(`monitor.start-rag.startmunich.de`)
      - traefik.http.routers.dashboard-http.entrypoints=web
      - traefik.http.routers.dashboard-http.middlewares=https-redirect
      - traefik.http.routers.dashboard-https.rule=Host(`monitor.start-rag.startmunich.de`)
      - traefik.http.routers.dashboard-https.entrypoints=webs
      - traefik.http.routers.dashboard-https.tls=true
      - traefik.http.routers.dashboard-https.service=dashboard
      - traefik.http.routers.dashboard-https.tls.certresolver=mycaresolver
      - traefik.http.services.dashboard.loadbalancer.server.port=3000

  vectordb_sync:
    hostname: vectordb_sync
    expose:
      - "5000"
    restart: always
    image: ghcr.io/startmunich/vectordb_sync:latest
    depends_on:
      - neo4j
      - qdrant
      - infinity
      - redis
    environment:
      NEO4J_URL: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASS: redbull_wildberry
      QDRANT_URL: http://qdrant:6333
      QDRANT_COLLECTION_NAME: startgpt
      INFINITY_URL: http://infinity:7997
      INFINITY_MODEL: BAAI/bge-large-en-v1.5

  slackcrawler:
    hostname: slackcrawler
    restart: always
    image: ghcr.io/startmunich/slackcrawler:latest
    depends_on:
      - vectordb_sync
      - neo4j
      - redis
    environment:
      NEO4J_URL: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASS: redbull_wildberry
      SLACK_APP_TOKEN: $SLACK_APP_TOKEN
      SLACK_BOT_TOKEN: $SLACK_BOT_TOKEN

  slackbot:
    hostname: slackbot
    restart: always
    image: ghcr.io/startmunich/slackbot:latest
    depends_on:
      - qdrant
      - infinity
    environment:
      QDRANT_URL: http://qdrant:6333
      QDRANT_COLLECTION_NAME: startgpt
      INFINITY_URL: http://infinity:7997
      INFINITY_MODEL: BAAI/bge-large-en-v1.5
      SLACK_APP_TOKEN: $SLACK_APP_TOKEN
      SLACK_BOT_TOKEN: $SLACK_BOT_TOKEN
      REPLICATE_API_TOKEN: $REPLICATE_API_TOKEN
      LLM_MODEL: mistralai/mixtral-8x7b-instruct-v0.1:2b56576fcfbe32fa0526897d8385dd3fb3d36ba6fd0dbe033c72886b81ade93e

  webcrawler:
    hostname: webcrawler
    restart: always
    image: ghcr.io/startmunich/webcrawler:latest
    depends_on:
      - neo4j
    environment:
      NEO4J_URL: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASS: redbull_wildberry

  meilisearch:
    hostname: meilisearch
    image: getmeili/meilisearch:v0.25.2
    environment:
      - MEILI_MASTER_KEY=redbull_blueberry
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=production
      - MEILI_DB_PATH=data.ms
    volumes:
      - ./data.ms:/data.ms
      - "$HOME/startgpt/meilisearch/data.ms:/data.ms"
    restart: unless-stopped

  influxdb:
    image: influxdb:2.6-alpine
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=startgpt
      - DOCKER_INFLUXDB_INIT_PASSWORD=$INFLUXDB_SETUP_PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG=start_munich
      - DOCKER_INFLUXDB_INIT_BUCKET=startgpt
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$INFLUXDB_ADMIN_TOKEN
    volumes:
      - $HOME/startgpt/influxdb:/var/lib/influxdb2:rw
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.influxdb-http.rule=Host(`influx.start-rag.startmunich.de`)
      - traefik.http.routers.influxdb-http.entrypoints=web
      - traefik.http.routers.influxdb-http.middlewares=https-redirect
      - traefik.http.routers.influxdb-https.rule=Host(`influx.start-rag.startmunich.de`)
      - traefik.http.routers.influxdb-https.entrypoints=webs
      - traefik.http.routers.influxdb-https.tls=true
      - traefik.http.routers.influxdb-https.service=influxdb
      - traefik.http.routers.influxdb-https.tls.certresolver=mycaresolver
      - traefik.http.services.influxdb.loadbalancer.server.port=8086

volumes:
  letsencrypt:
    name: letsencrypt
